"""The TraceStore port (DESIGN.md §6.6).

The core engine talks only to this interface, so a document-DB backend (MongoStore)
can drop in later without touching record/replay/branch.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..model import Event, Run, Snapshot


@runtime_checkable
class TraceStore(Protocol):
    def create_run(self, run: Run) -> None: ...
    def update_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run: ...
    def list_runs(self) -> list[Run]: ...

    def append_event(self, ev: Event) -> None: ...
    def events(self, run_id: str) -> list[Event]: ...

    def put_snapshot(self, snap: Snapshot) -> None: ...
    def snapshots(self, run_id: str) -> list[Snapshot]: ...

    def put_blob(self, data: bytes | Any) -> str: ...
    def get_blob(self, blob_id: str) -> bytes: ...

    def commit(self) -> None:
        """Flush buffered writes durably. Called when a record/replay session closes."""
